apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin
#    namespace: link-mysql
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
    selector:
        app: phpmyadmin-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
#  namespace: link-mysql
  labels:
    app: phpmyadmin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
      - name: phpmyadmin
        image: myphpmyadmin
        ports:
        - containerPort: 5000
          name: http
        imagePullPolicy: Never
