apiVersion: v1
kind: Service
metadata:
    name: wordpress
#    namespace: link-mysql
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
    selector:
        app: wordpress-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
#  namespace: link-mysql
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: mywordpress
        ports:
        - containerPort: 5050
          name: http
#        env:
#        - name: WORDPRESS_DB_HOST
#          value: mysql:3306
        imagePullPolicy: Never
