apiVersion: v1
kind: Service
metadata:
    name: ftps
    annotations:
        metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.232
    ports:
    - name: http
      port: 21
      targetPort: 21
      protocol: TCP
    selector:
        app: ftps-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
      - name: ftps
        image: myftps
        ports:
        - containerPort: 21
          name: http
        imagePullPolicy: Never
